(defparameter *bfo2-relations*
  '((is-part-of !obo:BFO_0000050 (:temporal :bfo2))
    (has-part !obo:BFO_0000051 (:temporal :bfo2))
    (inheres-in !obo:BFO_0000052 (:temporal :bfo2))
    (is-bearer-of !obo:BFO_0000053 (:temporal :bfo2))
    (is-realized-by !obo:BFO_0000054 (:temporal))
    (realizes !obo:BFO_0000055 (:temporal :bfo2))
    (participates-in !obo:BFO_0000056 (:temporal :bfo2))
    (has-participant !obo:BFO_0000057 (:temporal))
    (is-concretization-of !obo:BFO_0000058 )
    (concretizes !obo:BFO_0000059)
    (is-immediately-preceded-by !obo:BFO_0000060)
    (immediately-precedes !obo:BFO_0000061)
    (is-preceded-by !obo:BFO_0000062)
    (precedes !obo:BFO_0000063)
    (is-course-of !obo:BFO_0000064)
    (has-course !obo:BFO_0000065)
    (occurs-in !obo:BFO_0000066)
    (has-site-of !obo:BFO_0000067)
    (begins-to-exist-during !obo:BFO_0000068)
    (ceases-to-exist-during !obo:BFO_0000069)
    (s-depends-on !obo:BFO_0000070)
    (has-granular-part !obo:BFO_0000071)
    (has-granular-process-part !obo:BFO_0000072)
    (is-granular-part-of !obo:BFO_0000073)
    (is-granular-part-of-process !obo:BFO_0000074)
    (is-aggregate-of !obo:BFO_0000075)
    (is-fiat-part-of !obo:BFO_0000076)
    (has-participant-beginning-to-exist !obo:BFO_0000077)
    (has-participant-ceasing-to-exist !obo:BFO_0000078)
    (is-function-of !obo:BFO_0000079)
    (is-quality-of !obo:BFO_0000080)
    (is-role-of !obo:BFO_0000081)
    (is-located-in !obo:BFO_0000082)
    (is-located-at !obo:BFO_0000083)
    (g-depends-on !obo:BFO_0000084)
    (has-function !obo:BFO_0000085)
    (has-quality !obo:BFO_0000086)
    (has-role !obo:BFO_0000087)
    ))

(defun id-for-bfo-axiom (i)
  (make-uri nil (format nil "obo:BFO_~7,'0d" (+ i 10000))))

(defmacro with-label-vars-from (ont &body body)
  (let ((ontvar (make-symbol "ONT"))
	(classes (make-symbol "CLASSES")))
    `(let* ((,ontvar (load-ontology ,ont))
	   (,classes (mapcar (lambda(e) 
			       (list (intern (string-upcase (substitute #\- #\space (second e))))
				     (first e)))
			     (sparql '(:select (?class ?label) ()
				       (?class !rdf:type !owl:Class) 
				       (?class !rdfs:label ?label))
				     :kb ,ontvar :use-reasoner :none))))
       (progv (mapcar 'first ,classes) (mapcar 'second ,classes)
	 ,@body))))

(defun nax (id ax &optional label)
  "named axiom - id is a number. label is optional."
  `(,(first ax)  (annotation !obo:IAO_0010000 ,(id-for-bfo-axiom id))
     ,@(and label `((annotation !rdfs:label ,(format nil "~a@en" label))))
     ,@(cdr ax)))

(defun bfo2-relations ()
  (let ((definition !obo:IAO_0000115)
	(alternative-term !obo:IAO_0000118)
	(example-of-usage !obo:IAO_0000112)
	(editor-preferred-label !obo:IAO_0000111)
	(editor-note  !obo:IAO_0000116)
	(axiom-id !obo:IAO_0010000))
    (labels ((@en (s) (literal s "@en" s))
	     (label (thing s)  `(annotation-assertion !rdfs:label ,thing ,(@en s)))
	     (alternative-label (thing s)  `(annotation-assertion ,alternative-term ,thing ,(@en s)))
	     (definition (thing s)  `(annotation-assertion ,definition ,thing ,(@en s))))
      (with-ontology bfo-2-relations (:about !obo:bfo/core-relations.owl :collecting t)
	  ((progv (mapcar 'car *bfo2-relations*) (mapcar 'second *bfo2-relations*)
	     (with-label-vars-from "~/repos/bfo/trunk/src/ontology/owl-ruttenberg/bfo2-classes.owl"  
	       (asq (imports !obo:bfo/core-classes.owl))
	       (loop for (var uri) in *bfo2-relations* do
		    (as `(declaration (object-property ,uri))
			(label uri (substitute #\space #\- (string-downcase (string var)))))
		    (when (find #\- (string var))
		      (as (alternative-label uri (substitute #\_ #\- (#"replaceFirst" (string-downcase (string var)) "is-" "")))))
		    (if (#"matches" (string-downcase (string var)) "^is-.*")
			(as (alternative-label uri (substitute #\space #\- (#"replaceFirst" (string-downcase (string var)) "is-" ""))))
			))
	       (as
		`(declaration (annotation-property ,axiom-id))
		`(annotation-assertion !rdfs:label ,axiom-id "axiom id")
		`(declaration (annotation-property ,example-of-usage))
		`(declaration (annotation-property ,editor-preferred-label))
		`(declaration (annotation-property ,alternative-term))
		`(declaration (annotation-property ,definition))
		`(declaration (annotation-property ,editor-note)))
	       (as
		(nax 1 `(object-property-domain ,is-part-of ,entity) "domain of part of")
		(nax 2 `(object-property-range ,is-part-of ,entity))
		(nax 70 `(transitive-object-property ,is-part-of))
		(nax 3 `(inverse-object-properties ,is-part-of ,has-part))
		(nax 4 `(object-property-domain ,has-participant ,process))
		(nax 5 `(object-property-range ,has-participant ,continuant))
		(nax 6 `(inverse-object-properties ,has-participant ,participates-in))
		(nax 7 `(object-property-domain ,is-bearer-of ,independent-continuant))
		(nax 8 `(object-property-range ,is-bearer-of ,dependent-continuant))
		(nax 9 `(inverse-object-properties ,inheres-in ,is-bearer-of))
		(nax 10 `(object-property-domain ,has-course ,continuant))
		(nax 11 `(object-property-range ,has-course ,process))
		(nax 12 `(inverse-object-properties ,has-course ,is-course-of))
		(nax 13 `(transitive-object-property ,has-part))
		(nax 14 `(functional-object-property ,inheres-in))
		(nax 15 `(object-property-domain ,immediately-precedes ,process))
		(nax 16 `(object-property-range ,immediately-precedes ,process))
		(nax 17 `(inverse-object-properties ,immediately-precedes ,is-immediately-preceded-by))

		(nax 19 `(object-property-domain ,precedes ,process))
		(nax 20 `(object-property-range ,precedes ,process))
		(nax 21 `(inverse-object-properties ,precedes ,is-preceded-by))
		(nax 22 `(sub-object-property-of ,is-immediately-preceded-by ,is-preceded-by))
		(nax 23 `(sub-object-property-of ,immediately-precedes ,precedes))
		(nax 24 `(object-property-domain ,occurs-in ,process))

		(nax 25 `(object-property-range ,occurs-in ,independent-continuant))
		(nax 26 `(inverse-object-properties ,occurs-in ,has-site-of))
		(nax 27 `(sub-object-property-of (object-property-chain ,is-part-of ,occurs-in) ,occurs-in) ) ;"part a process that occurs in C occurs in C")
		(nax 18 `(sub-object-property-of (object-property-chain ,occurs-in ,is-part-of) ,occurs-in)) ;"if p occurs in c, then p occurs in anything that c is part of")

		(nax 28 `(transitive-object-property ,precedes))



		(nax 29 `(transitive-object-property ,is-preceded-by))
		(nax 30 `(functional-object-property ,is-immediately-preceded-by))
		(nax 31 `(functional-object-property ,immediately-precedes))
		(nax 32 `(object-property-domain ,concretizes ,specifically-dependent-continuant))
		(nax 33 `(object-property-range ,concretizes ,generically-dependent-continuant))
		(nax 34 `(inverse-object-properties ,concretizes ,is-concretization-of))
		(nax 35 `(object-property-domain ,realizes ,process))
		(nax 36 `(object-property-range ,realizes ,realizable-entity))
		(nax 37 `(inverse-object-properties ,realizes ,is-realized-by))
		(nax 38 `(sub-object-property-of (object-property-chain ,realizes ,inheres-in) ,has-participant)) ; "bearers of realizables participate in their realizaton")  ; note OWLAPI bug.

                (nax 39 `(inverse-object-properties ,begins-to-exist-during ,ceases-to-exist-during))
;		(nax 40 `(sub-object-property-of ,is-concretization-of ,s-depends-on))
		(nax 41 `(sub-object-property-of ,inheres-in ,s-depends-on))
		(nax 42 `(object-property-domain ,inheres-in ,dependent-continuant))
		(nax 43 `(object-property-range ,inheres-in ,independent-continuant))
		(nax 44 `(object-property-domain ,is-concretization-of ,generically-dependent-continuant))
		(nax 45 `(object-property-range ,is-concretization-of ,specifically-dependent-continuant))
		(nax 46 `(object-property-domain ,begins-to-exist-during ,continuant))
		(nax 47 `(object-property-domain ,ceases-to-exist-during ,continuant))
		(nax 48 `(object-property-range  ,begins-to-exist-during ,process))
		(nax 49 `(object-property-range  ,ceases-to-exist-during ,process))
		(nax 50 `(object-property-domain ,is-granular-part-of-process ,process))
		(nax 51 `(object-property-range ,is-granular-part-of-process ,process))
		(nax 52 `(object-property-range  ,is-granular-part-of ,material-entity))
		(nax 53 `(object-property-domain  ,is-granular-part-of ,material-entity))
		(nax 54 `(inverse-object-properties ,is-granular-part-of-process ,has-granular-process-part))
		(nax 55 `(inverse-object-properties ,is-granular-part-of ,has-granular-part))
		(nax 56 `(sub-object-property-of ,has-granular-process-part ,has-part))
		(nax 57 `(sub-object-property-of ,has-granular-part ,has-part))
		(nax 58 `(sub-object-property-of ,is-granular-part-of ,is-part-of))
		(nax 59 `(sub-object-property-of ,is-granular-part-of-process ,is-part-of))
		(nax 60 `(sub-object-property-of ,begins-to-exist-during ,participates-in))
		(nax 61 `(sub-object-property-of ,ceases-to-exist-during ,participates-in))
		(nax 62 `(sub-object-property-of ,is-fiat-part-of ,is-part-of))
		(nax 63 `(sub-object-property-of ,is-aggregate-of ,is-part-of))
		(nax 64 `(sub-object-property-of ,has-participant-ceasing-to-exist ,has-participant))
		(nax 65 `(sub-object-property-of ,has-participant-beginning-to-exist ,has-participant))
		(nax 66 `(inverse-object-properties ,has-participant-beginning-to-exist ,begins-to-exist-during))
		(nax 67 `(inverse-object-properties ,has-participant-ceasing-to-exist ,ceases-to-exist-during))
		(nax 68 `(sub-object-property-of ,is-course-of ,has-participant))
		(nax 69 `(sub-object-property-of ,has-course ,participates-in))
		(nax 71 `(sub-object-property-of ,is-role-of ,inheres-in))
		(nax 72 `(sub-object-property-of ,is-function-of ,inheres-in))
		(nax 73 `(sub-object-property-of ,is-quality-of ,inheres-in))
		(nax 74 `(object-property-domain ,is-quality-of ,quality))
		(nax 75 `(object-property-domain ,is-role-of ,role))
		(nax 76 `(object-property-domain ,is-function-of ,function))
		(nax 77 `(object-property-domain ,s-depends-on ,specifically-dependent-continuant))
		(nax 78 `(object-property-domain ,g-depends-on ,generically-dependent-continuant))
		(nax 79 `(object-property-range ,s-depends-on ,independent-continuant))
		(nax 80 `(object-property-range ,g-depends-on ,independent-continuant))
		(nax 81 `(sub-object-property-of ,inheres-in ,s-depends-on))
		(nax 82 `(sub-object-property-of ,is-part-of ,is-located-in))
		))))
	(write-rdfxml bfo-2-relations "~/repos/bfo/trunk/src/ontology/bfo2-relations.owl")))))
		
;(bfo2-relations)
	     
'(def-metadata concretizes bfo2-relations
  :editor-note
  "A generically dependent continuant may inhere in more than one entity. It does so by virtue of the fact that there is, for each entity that it inheres, a specifically dependent *concretization* of the generically dependent continuant that is specifically dependent. For instance, consider a story, which is an information artifact that inheres in some number of books. Each book bears some quality that carries the story. The relation between this quality and the generically dependent continuant is that the former is the concretization of the latter."
  :definition
  "a relationship between a generically dependent continuant and at least one specifically dependent continuant upon which it existentially depends"
  :definition-editor
  "Alan Ruttenberg"
  :definition-editor
  "Barry Smith")


;(def-axiom 1 bfo 
;  `(object-property-domain ,is-part-of ,entity)
;  "domain of part of")



;(with-label-vars-from "~/repos/bfo/trunk/src/ontology/bfo2.owl"  entity) -> !obo:BFO_0000001

;; these axioms violate global constaints
;		(nax 18 `(irreflexive-object-property ,is-immediately-preceded-by)) 
;		(nax 19 `(irreflexive-object-property ,immediately-precedes))
;		(nax 20 `(asymmetric-object-property ,is-immediately-preceded-by))
;		(nax 21 `(asymmetric-object-property ,immediately-precedes))
	   
;		(nax 24 `(irreflexive-object-property ,is-preceded-by)) 
;		(nax 25 `(irreflexive-object-property ,precedes))
;		(nax 26 `(asymmetric-object-property ,is-preceded-by))
;		(nax 27 `(asymmetric-object-property ,precedes))
