((annotation !rdfs:comment "This is an early version of BFO version 2 and has not yet been extensively reviewed by the project team members. Please see the project site http://code.google.com/p/bfo/ , the bfo2 owl discussion group http://groups.google.com/group/bfo-owl-devel , the bfo2 discussion group http://groups.google.com/group/bfo-devel, the tracking google doc http://goo.gl/IlrEE, and the current version of the bfo2 reference http://purl.obolibrary.org/obo/bfo/dev/bfo2-reference.docx . This ontology is generated from a specification at http://bfo.googlecode.com/svn/trunk/src/ontology/owl-group/specification/ and with the code that generates the OWL version in http://bfo.googlecode.com/svn/trunk/src/tools/. A very early version of BFO version 2 in CLIF is at http://purl.obolibrary.org/obo/bfo/dev/bfo.clif@en")
 :source "Alan Ruttenberg"
 :id 100)

(annotation !foaf:homepage !<http://code.google.com/p/bfo/>)
(annotation !foaf:homepage !<http://ifomis.org/bfo>)
(annotation !foaf:mbox !<mailto:bfo-owl-devel@googlegroups.com>)
(annotation !rdfs:seeAlso !<http://groups.google.com/group/bfo-owl-devel>)
(annotation !rdfs:seeAlso !<http://groups.google.com/group/bfo-devel>)
(annotation !rdfs:seeAlso !<http://groups.google.com/group/bfo-discuss>)
(annotation !rdfs:seeAlso !<http://goo.gl/bIlrEE>)
(annotation !rdfs:seeAlso !<http://bfo.googlecode.com/svn/trunk/src/tools/>)
(annotation !rdfs:isDefinedBy !<http://purl.obolibrary.org/obo/bfo/dev/bfo.clif>)
(annotation !rdfs:isDefinedBy !<http://purl.obolibrary.org/obo/bfo/2012-07-20/Reference>)
(annotation !rdfs:isDefinedBy !<http://purl.obolibrary.org/obo/bfo/2012-07-20/ReleaseNotes>)
(annotation !rdfs:isDefinedBy !<http://bfo.googlecode.com/svn/trunk/src/ontology/owl-group/specification/>)

(annotation !dc:license !<http://creativecommons.org/licenses/by/3.0/>)

(annotation !dc:contributor "Mauricio Almeida")
(annotation !dc:contributor "Thomas Bittner")
(annotation !dc:contributor "Jonathan Bona")
(annotation !dc:contributor "Mathias Brochhausen")
(annotation !dc:contributor "Werner Ceusters")
(annotation !dc:contributor "Melanie Courtot")
(annotation !dc:contributor "Randall Dipert")
(annotation !dc:contributor "Bill Duncan")
(annotation !dc:contributor "Janna Hastings")
(annotation !dc:contributor "Albert Goldfain")
(annotation !dc:contributor "Leonard Jacuzzo")
(annotation !dc:contributor "Ludger Jansen")
(annotation !dc:contributor "Pierre Grenon")
(annotation !dc:contributor "Larry Hunter")
(annotation !dc:contributor "Chris Mungall")
(annotation !dc:contributor "Fabian Neuhaus")
(annotation !dc:contributor "David Osumi-Sutherland")
(annotation !dc:contributor "Bjoern Peters")
(annotation !dc:contributor "Mark Ressler")
(annotation !dc:contributor "Robert Rovetto")
(annotation !dc:contributor "Ron Rudnicki")
(annotation !dc:contributor "Alan Ruttenberg")
(annotation !dc:contributor "Stefan Schulz")
(annotation !dc:contributor "Barry Smith")
(annotation !dc:publisher "Alan Ruttenberg")
